sudo: required
dist: bionic
before_install:
    - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latexmk texlive-lang-german texlive-font-utils texlive-science texlive-pictures rubber graphviz inkscape python3-opencv lmodern  texlive-bibtex-extra biber
      
git:
    submodules: false 

script:
    - mkdir output
    - cd Thesis
    - make
    - mv main_mrm.pdf ../output/Thesis.pdf
    - cd ../Presentation
    - make
    - mv main.pdf ../output/Presentation.pdf

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: output
    on:
        branch: master
